version: '3.8'

services:
  react-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`country.tabw.dev`)"
      - "traefik.http.routers.react-app.entrypoints=web"

networks:
  web-network:
    external: true